runtime: nodejs18
instance_class: F2
service: frontend
env: standard

handlers:
  # Serve the main entry point (index.html) for your Single Page Application (SPA)
  - url: /
    static_files: build/index.html
    upload: build/index.html

  # Catch-all for serving static assets and other subroutes
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
error_handlers:
  - file: build/index.html