runtime: custom
instance_class: F2
service: frontend1
env: flex

handlers:
  # Serve all static files with their exact paths
  - url: /static
    static_dir: build/static

  # Serve main entry point for all other paths
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
error_handlers:
  - file: build/index.html